
development:
  adapter: postgresql
  database: app-dev
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: app-dev
  host: localhost
